version: '3'
services:
    pgsql:
      image: 'postgres:13'
      ports:
          - '${FORWARD_PGSQL_PORT:-5432}:5432'
      environment:
          PGPASSWORD: '${PGSQL_DB_PASSWORD:-secret}'
          POSTGRES_DB: '${PGSQL_DB_DATABASE}'
          POSTGRES_USER: '${PGSQL_DB_USERNAME}'
          POSTGRES_PASSWORD: '${PGSQL_DB_PASSWORD:-secret}'
      volumes:
          - 'infra-pgsql:/var/lib/postgresql/data'
      networks:
          - infra
      healthcheck:
          test: ["CMD", "pg_isready", "-q", "-d", "${PGSQL_DB_DATABASE}", "-U", "${PGSQL_DB_USERNAME}"]
          retries: 3
          timeout: 5s
    mysql:
        image: 'mysql/mysql-server:5.7'
        ports:
            - '${FORWARD_MYSQL_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${MYSQL_DB_DATABASE}'
            MYSQL_USER: '${MYSQL_DB_USERNAME}'
            MYSQL_PASSWORD: '${MYSQL_DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'infra-mysql:/var/lib/mysql'
        networks:
            - infra
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    mongodb:
        image: 'mongo:latest'
        ports:
            - '${FORWARD_MONGODB_PORT:-27017}:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGODB_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_PASSWORD}'
            MONGO_INITDB_DATABASE: '${MONGODB_DATABASE}'
        volumes:
            - 'infra-mongodb:/data/db'
        networks:
            - infra
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 40s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'infra-redis:/data'
        networks:
            - infra
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - infra
networks:
    infra:
        driver: bridge
volumes:
    infra-pgsql:
        driver: local
    infra-mysql:
        driver: local
    infra-mongodb:
        driver: local
    infra-redis:
        driver: local